language: python
python:
  - 3.6
  - 3.7

install: 
  - pip install -r requirements.txt
  - pip install -r requirements-dask.txt
  - export LD_LIBRARY_PATH="`pwd`/croaring:$LD_LIBRARY_PATH"
  - python setup.py install

script: python setup.py nosetests
